/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AResult: typeof import('antdv-next')['Result']
    ATag: typeof import('antdv-next')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('antdv-next')['Alert']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const ADescriptions: typeof import('antdv-next')['Descriptions']
  const ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AEmpty: typeof import('antdv-next')['Empty']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputPassword: typeof import('antdv-next')['InputPassword']
  const ALayout: typeof import('antdv-next')['Layout']
  const ALayoutContent: typeof import('antdv-next')['LayoutContent']
  const ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
  const ALayoutSider: typeof import('antdv-next')['LayoutSider']
  const AMenu: typeof import('antdv-next')['Menu']
  const AResult: typeof import('antdv-next')['Result']
  const ATag: typeof import('antdv-next')['Tag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}