/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AAvatar: typeof import('antdv-next')['Avatar']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACheckboxGroup: typeof import('antdv-next')['CheckboxGroup']
    ACollapse: typeof import('antdv-next')['Collapse']
    ACollapsePanel: typeof import('antdv-next')['CollapsePanel']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AModal: typeof import('antdv-next')['Modal']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    APopover: typeof import('antdv-next')['Popover']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARangePicker: typeof import('antdv-next')['DateRangePicker']
    AResult: typeof import('antdv-next')['Result']
    ASelect: typeof import('antdv-next')['Select']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASpace: typeof import('antdv-next')['Space']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    ATreeSelect: typeof import('antdv-next')['TreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('antdv-next')['Alert']
  const AAvatar: typeof import('antdv-next')['Avatar']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const ACheckboxGroup: typeof import('antdv-next')['CheckboxGroup']
  const ACollapse: typeof import('antdv-next')['Collapse']
  const ACollapsePanel: typeof import('antdv-next')['CollapsePanel']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADescriptions: typeof import('antdv-next')['Descriptions']
  const ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
  const ADrawer: typeof import('antdv-next')['Drawer']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AEmpty: typeof import('antdv-next')['Empty']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputNumber: typeof import('antdv-next')['InputNumber']
  const AInputPassword: typeof import('antdv-next')['InputPassword']
  const ALayout: typeof import('antdv-next')['Layout']
  const ALayoutContent: typeof import('antdv-next')['LayoutContent']
  const ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
  const ALayoutSider: typeof import('antdv-next')['LayoutSider']
  const AMenu: typeof import('antdv-next')['Menu']
  const AModal: typeof import('antdv-next')['Modal']
  const APopconfirm: typeof import('antdv-next')['Popconfirm']
  const APopover: typeof import('antdv-next')['Popover']
  const ARadioGroup: typeof import('antdv-next')['RadioGroup']
  const ARangePicker: typeof import('antdv-next')['DateRangePicker']
  const AResult: typeof import('antdv-next')['Result']
  const ASelect: typeof import('antdv-next')['Select']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ASpace: typeof import('antdv-next')['Space']
  const ATable: typeof import('antdv-next')['Table']
  const ATag: typeof import('antdv-next')['Tag']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const ATree: typeof import('antdv-next')['Tree']
  const ATreeSelect: typeof import('antdv-next')['TreeSelect']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}